resolver: lts-5.11

# Uh, I guess this can't be empty:
# packages: []
packages:
- '.'

extra-deps:
- accelerate-0.15.1.0
- accelerate-cuda-0.15.1.1
- accelerate-examples-0.15.1.0
- accelerate-fft-0.15.1.0
- accelerate-io-0.15.1.0
- cuda-0.7.0.0
- language-c-quote-0.11.6
- mainland-pretty-0.4.1.3
- normaldistribution-1.1.0.3
- cufft-0.1.2.2
- exception-mtl-0.4
- symbol-0.2.4
- criterion-1.1.0.0

- gloss-accelerate-1.9.0.0
- gloss-raster-accelerate-1.9.0.0

# - gloss-1.10.1.1
# - gloss-rendering-1.10.1.1

# Old Gloss needs old OpenGL
- gloss-1.9.4.1
- gloss-rendering-1.9.3.1
- OpenGL-2.12.0.0
- GLURaw-1.5.0.3
- OpenGLRaw-2.4.1.0

# Override default flag values for local packages and extra-deps
flags:
  accelerate:
    unsafe-checks: false
    bounds-checks: true
    debug: false
    internal-checks: false
  accelerate-examples:
    canny: false
    crystal: true
    fft: true
    fluid: true
    hashcat: true
    kmeans: true
    mandelbrot: true
    nbody: true
    pagerank: true
    ray: true
    smoothelife: true
    smvm: true

# Extra package databases containing global packages
extra-package-dbs: []
